language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - TRACY=~2.4.0
    - TRACY=~2.5.0
    - TRACY=~2.6.0

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TRACY=~2.4.0 COMPOSER_EXTRA_ARGS="--prefer-lowest --prefer-stable"
    - php: 7.1
      env: TRACY=~2.5.0 COMPOSER_EXTRA_ARGS="--prefer-lowest --prefer-stable"
    - php: 7.1
      env: TRACY=~2.6.0 COMPOSER_EXTRA_ARGS="--prefer-lowest --prefer-stable"

before_install:
  - php .travis.composer.php

install:
  - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_EXTRA_ARGS

script:
  - vendor/bin/parallel-lint -e php,phpt src
  - vendor/bin/phpcs -sp --standard=vendor/nella/coding-standard/Nella/ruleset.xml src
